const dom = {
  byId: (id) => document.getElementById(id),
  connStatus: document.getElementById('connStatus'),
  toggleConnBtn: document.getElementById('toggleConnBtn'),
  chatArea: document.getElementById('chatArea'),
  msgInput: document.getElementById('msgInput'),
  sendBtn: document.getElementById('sendBtn'),
  fileBtn: document.getElementById('fileBtn'),
  typingIndicator: document.getElementById('typingIndicator'),
  myIdLoading: document.getElementById('myIdLoading'),
  myId: document.getElementById('myId'),
  usernameInput: document.getElementById('usernameInput'),
  peerId: document.getElementById('peerId'),
  typingName: document.getElementById('typingName'),
  messages: document.getElementById('messages'),
  fileInput: document.getElementById('fileInput'),
  progress: document.getElementById('progress'),
  progressName: document.getElementById('progressName'),
  progressBar: document.getElementById('progressBar'),
  progressText: document.getElementById('progressText'),
  progressTrack: document.getElementById('progressTrack'),
  qrcode: document.getElementById('qrcode'),
  qrcodeContainer: document.getElementById('qrcodeContainer'),
  chatInputContainer: document.getElementById('chatInputContainer'),
  toast: document.getElementById('toast'),
  filePreviewName: document.getElementById('filePreviewName'),
  filePreviewContent: document.getElementById('filePreviewContent'),
};
